commit_message: '[skip ci]'
pull_request_title: '[docs] Sync translations with Crowdin'
pull_request_labels: [ l10n ]
files:
  - source: "/i18n/en/*.json"
    translation: "/i18n/%two_letters_code%/%original_file_name%"
