version: '3'
services:
  next-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes:
      - .env:/app/.env
    ports:
      - "8082:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - next-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
